In [ ]:
# photosCLEFparsefinal.py

import xml.etree.ElementTree as ET
import pandas as pd

def parse_photos_CLEF(file_name='photosCLEF.xml'):
    """
    Parse photosCLEF.xml and extract:
      - photo_id, dateuploaded
      - latitude, longitude (from <location>)
      - title, description
      - owner_username, user_id (nsid), owner_location
    Returns a pandas DataFrame.
    """
    tree = ET.parse(file_name)
    root = tree.getroot()

    data = []
    for photo in root.findall('photo'):
        # Basic attributes
        photo_id     = photo.get('id')
        dateuploaded = photo.get('dateuploaded')

        # Geo‐tags under <location>
        loc_elem = photo.find('location')
        if loc_elem is not None:
            lat_str  = loc_elem.get('latitude')
            lon_str  = loc_elem.get('longitude')
            latitude  = float(lat_str)  if lat_str  is not None else None
            longitude = float(lon_str)  if lon_str  is not None else None
        else:
            latitude = None
            longitude = None

        # Title and description
        title_elem = photo.find('title')
        desc_elem  = photo.find('description')
        title       = title_elem.text      if title_elem is not None else None
        description = desc_elem.text       if desc_elem  is not None else None

        # Owner info: username, nsid (user_id), location
        owner_elem     = photo.find('owner')
        if owner_elem is not None:
            username = owner_elem.get('username')
            nsid     = owner_elem.get('nsid')
            location = owner_elem.get('location')
        else:
            username = None
            nsid     = None
            location = None

        data.append({
            'photo_id'      : photo_id,
            'dateuploaded'  : dateuploaded,
            'latitude'      : latitude,
            'longitude'     : longitude,
            'title'         : title,
            'description'   : description,
            'owner_username': username,
            'user_id'       : nsid,
            'owner_location': location
        })

    df = pd.DataFrame(data)

    # Convert dateuploaded from epoch seconds to datetime
    if df['dateuploaded'].notnull().all():
        df['dateuploaded'] = pd.to_datetime(
            pd.to_numeric(df['dateuploaded'], errors='coerce'),
            unit='s', errors='coerce'
        )

    return df

if __name__ == '__main__':
    # Ensure pandas will show all columns
    pd.set_option('display.max_columns', None)

    # Parse and load the DataFrame
    df = parse_photos_CLEF('photosCLEF.xml')

    # Specify columns to display (including the new user_id)
    cols = [
        'photo_id', 'dateuploaded',
        'latitude', 'longitude',
        'title', 'description',
        'owner_username', 'user_id', 'owner_location'
    ]

    print("Extracted photo records from photosCLEF.xml:")
    print(df[cols].head(10))
    print(f"\nTotal records: {len(df)}")

Extracted photo records from photosCLEF.xml:
     photo_id        dateuploaded   latitude   longitude  \
0  2109698205 2007-12-14 07:44:18  37.794833 -122.401334
1  2172469872 2008-01-06 17:07:08        NaN         NaN
2   830593398 2007-07-16 19:04:27        NaN         NaN
3  2226919732 2008-01-28 20:07:00  55.765685   37.630110
4   798067744 2007-07-13 10:22:26        NaN         NaN
5  2162084627 2008-01-03 14:50:11        NaN         NaN
6  2516831585 2008-05-24 01:31:22        NaN         NaN
7  2145166304 2007-12-28 23:38:32        NaN         NaN
8  2330883810 2008-03-13 07:51:26        NaN         NaN
9  1912488787 2007-11-08 04:52:37        NaN         NaN

                                title  \
0                   Launch Day donuts
1                   Old and Knackered
2                               Boats
3                           Отпевание
4                          Precarious
5                       Inquietudine.
6                              Capter
7               last ferry of the day
8  Line 'em up just to knock 'em down
9                    Rainbow Bookcase

                                         description     owner_username  \
0                 Hello, Stats! Hello, Uploadrrrrrr!          waferbaby
1  Don't fret about which is which, it's pretty m...        me'nthedogs
2                                               None           Monster.
3  Чин погребения приснопамятного <a target="_bla...          И. Максим
4                         Lake Phalen, Maplewood, MN         *clairity*
5  Il mio primo scatto con la nuova Nikon D40.\nN...       LunaDiRimmel
6                                               None        pichenettes
7                                               None            g_cowan
8                                               None        unsure shot
9  I aligned my books in honor of the Rainbow Sna...  Eccentric Scholar

           user_id       owner_location
0  51035718466@N01   San Francisco, USA
1     66176388@N00         Williton, UK
2     66201174@N00
3     16185355@N00               France
4     38315261@N00
5     77251992@N00
6     52163187@N00        Paris, France
7     32399776@N00  ardrossan, scotland
8     46162062@N00          Los Angeles
9      7772579@N08       Durham, NC, US

Total records: 4546

In [ ]:
import folium

canada_map = folium.Map(location=[17.498449, 78.384659], zoom_start=20)

canada_map
folium.Marker()

In [ ]:
# photosMIRparsefinal.py

import xml.etree.ElementTree as ET
import pandas as pd

def parse_photos_MIR(file_name='photosMIR.xml'):
    """
    Parse photosMIR.xml and extract:
      - photo_id, dateuploaded
      - latitude, longitude (from <location>)
      - title, description
      - owner_username, user_id (nsid), owner_location
    Returns a pandas DataFrame.
    """
    tree = ET.parse(file_name)
    root = tree.getroot()

    data = []
    for photo in root.findall('photo'):
        # Basic attributes
        photo_id     = photo.get('id')
        dateuploaded = photo.get('dateuploaded')

        # Geo‐tags under <location>
        loc_elem = photo.find('location')
        if loc_elem is not None:
            lat_str  = loc_elem.get('latitude')
            lon_str  = loc_elem.get('longitude')
            latitude  = float(lat_str)  if lat_str  is not None else None
            longitude = float(lon_str)  if lon_str  is not None else None
        else:
            latitude = None
            longitude = None

        # Title and description
        title       = photo.findtext('title')
        description = photo.findtext('description')

        # Owner info: username, nsid (user_id), location
        owner_elem = photo.find('owner')
        if owner_elem is not None:
            username = owner_elem.get('username')
            nsid     = owner_elem.get('nsid')
            location = owner_elem.get('location')
        else:
            username = None
            nsid     = None
            location = None

        data.append({
            'photo_id'      : photo_id,
            'dateuploaded'  : dateuploaded,
            'latitude'      : latitude,
            'longitude'     : longitude,
            'title'         : title,
            'description'   : description,
            'owner_username': username,
            'user_id'       : nsid,
            'owner_location': location
        })

    df = pd.DataFrame(data)

    # Convert dateuploaded from epoch seconds to datetime
    if df['dateuploaded'].notnull().all():
        df['dateuploaded'] = pd.to_datetime(
            pd.to_numeric(df['dateuploaded'], errors='coerce'),
            unit='s', errors='coerce'
        )

    return df

if __name__ == '__main__':
    # Show all columns when printing
    pd.set_option('display.max_columns', None)

    # Parse and load the DataFrame
    df = parse_photos_MIR('photosMIR.xml')

    # Specify columns to display (including the new user_id)
    cols = [
        'photo_id', 'dateuploaded',
        'latitude', 'longitude',
        'title', 'description',
        'owner_username', 'user_id', 'owner_location'
    ]

    print("Extracted photo records from photosMIR.xml:")
    print(df[cols].head(10))              # show first 10 rows
    print(f"\nTotal records: {len(df)}")

Extracted photo records from photosMIR.xml:
     photo_id        dateuploaded   latitude   longitude  \
0  1595340828 2007-10-17 04:45:10  38.232417 -122.636652
1  2109698205 2007-12-14 07:44:18  37.794833 -122.401334
2   579495912 2007-06-21 07:20:41        NaN         NaN
3  2172469872 2008-01-06 17:07:08        NaN         NaN
4   522978795 2007-05-31 09:11:30  58.974259    6.171226
5   830593398 2007-07-16 19:04:27        NaN         NaN
6  1293010709 2007-09-01 11:17:02        NaN         NaN
7  2199591364 2008-01-17 11:13:25        NaN         NaN
8  2226919732 2008-01-28 20:07:00  55.765685   37.630110
9  1696615075 2007-10-22 21:29:25  46.233708    7.363619

                      title  \
0             Hairy Eyeball
1         Launch Day donuts
2                  konstruk
3         Old and Knackered
4       On top of the world
5                     Boats
6          salty bitterness
7  Apple & Ikea in my heart
8                 Отпевание
9

                                         description    owner_username  \
0                                      Hairy Eyeball       Leo Laporte
1                 Hello, Stats! Hello, Uploadrrrrrr!         waferbaby
2                               Design: Karim Rashid  Rodrigo Quiñones
3  Don't fret about which is which, it's pretty m...       me'nthedogs
4                    Preikestolen, Lysefjord, Norway          <Benoît>
5                                                             Monster.
6  &quot;The four o'clock sun wasn't too hot, but...         dirtyfeet
7                          Il mio angolo di paradiso       fabbriciuse
8  Чин погребения приснопамятного <a target="_bla...         И. Максим
9  Pues como Espejito se muere por mis fotos popu...          Marooned

           user_id        owner_location
0     52182314@N00                   USA
1  51035718466@N01    San Francisco, USA
2     53401406@N00     Helsinki, Finland
3     66176388@N00          Williton, UK
4     43216760@N00     Stockholm, Sweden
5     66201174@N00
6     21897733@N00  Texas, United States
7     11292446@N00           Rome, Italy
8     16185355@N00                France
9     88111659@N00    Portugalete, Spain

Total records: 14460

In [ ]:
foliumm.marker()

NameError: name 'foliumm' is not defined

In [ ]:
# photosPASCALparsefinal.py

import xml.etree.ElementTree as ET
import pandas as pd

def parse_photos_PASCAL(file_name='photosPASCAL.xml'):
    """
    Parse photosPASCAL.xml and extract:
      - photo_id, dateuploaded
      - latitude, longitude (from <location> if present)
      - title, description
      - owner_username, user_id (nsid), owner_location
    Returns a pandas DataFrame.
    """
    tree = ET.parse(file_name)
    root = tree.getroot()

    data = []
    for photo in root.findall('photo'):
        # Basic attributes
        photo_id     = photo.get('id')
        dateuploaded = photo.get('dateuploaded')

        # Geo‐tags under <location>
        loc_elem = photo.find('location')
        if loc_elem is not None:
            lat_str  = loc_elem.get('latitude')
            lon_str  = loc_elem.get('longitude')
            latitude  = float(lat_str)  if lat_str  is not None else None
            longitude = float(lon_str)  if lon_str  is not None else None
        else:
            latitude = None
            longitude = None

        # Title and description
        title       = photo.findtext('title')
        description = photo.findtext('description')

        # Owner info: username, nsid (user_id), location
        owner_elem = photo.find('owner')
        if owner_elem is not None:
            username = owner_elem.get('username')
            nsid     = owner_elem.get('nsid')
            location = owner_elem.get('location')
        else:
            username = None
            nsid     = None
            location = None

        data.append({
            'photo_id'      : photo_id,
            'dateuploaded'  : dateuploaded,
            'latitude'      : latitude,
            'longitude'     : longitude,
            'title'         : title,
            'description'   : description,
            'owner_username': username,
            'user_id'       : nsid,
            'owner_location': location
        })

    df = pd.DataFrame(data)

    # Convert dateuploaded from epoch seconds to datetime
    if df['dateuploaded'].notnull().all():
        df['dateuploaded'] = pd.to_datetime(
            pd.to_numeric(df['dateuploaded'], errors='coerce'),
            unit='s', errors='coerce'
        )

    return df

if __name__ == '__main__':
    # Show all columns when printing
    pd.set_option('display.max_columns', None)

    # Parse and load the DataFrame
    df = parse_photos_PASCAL('photosPASCAL.xml')

    # Specify columns to display (including the new user_id)
    cols = [
        'photo_id', 'dateuploaded',
        'latitude', 'longitude',
        'title', 'description',
        'owner_username', 'user_id', 'owner_location'
    ]

    print("Extracted photo records from photosPASCAL.xml:")
    print(df[cols].head(10))              # show first 10 rows
    print(f"\nTotal records: {len(df)}")

Extracted photo records from photosPASCAL.xml:
     photo_id        dateuploaded  latitude  longitude  \
0   111604571 2006-03-12 23:28:10       NaN        NaN
1  1424421677 2007-09-22 22:17:54       NaN        NaN
2   311153386 2006-12-01 15:12:51       NaN        NaN
3  1046908157 2007-08-08 05:50:32       NaN        NaN
4   109786962 2006-03-08 21:00:05       NaN        NaN
5  2124011227 2007-12-20 10:58:03       NaN        NaN
6  2644219324 2008-07-06 23:39:46       NaN        NaN
7   104779213 2006-02-26 19:11:21       NaN        NaN
8   102175481 2006-02-20 16:42:56       NaN        NaN
9  2873456984 2008-09-20 19:07:47       NaN        NaN

                                             title  \
0                                         CIMG9824
1                               Rose in winebottle
2                                 f-15_afterburner
3                                   Railfan heaven
4                               jorg and olif bike
5                                 Lonely Furniture
6             Macintosh and Apple 1 (1976 to 1984)
7                     Plymouth Citybus 043 X143CFJ
8  Jonas__2_yrs[1]._Handknit_sweater_from_Grandma.
9                                      Jeu de vent

                                         description owner_username  \
0                   2006_03_11 - Motor show Geneva -          dnl82
1  Same rose and bottle as previous picture but a...  mackelundberg
2  A good shot of the F-15C's twin P&amp;W F100 t...  flicker_boone
3                                                     Josh Thompson
4          steel, nederlander-style with cool basket      Uncleweed
5  As I walked into the living room my boots made...       ephidryn
6                                                       BrendanChoi
7             Dennis Dart SLF Plaxton 43 Seats\n2004    didbygraham
8                                                      PeterSchammy
9      Le vent joue avec la jupe de la chaise-longue       Regard81

        user_id                             owner_location
0  52734910@N00
1  10099287@N08                                     Sweden
2  72179310@N00  Wichita, Kansas, United States of America
3  83194813@N00                             Thoiry, France
4  56205607@N00                    North Vancouver, CANADA
5  97152890@N00
6  33366792@N00
7  13232346@N00                          Plymouth, England
8  60316175@N00                             Ottawa, Canada
9  29690662@N03

Total records: 10189

In [ ]:
import pandas as pd

# 1) Run your parsers
df_clef   = parse_photos_CLEF(   'photosCLEF.xml')
df_mir    = parse_photos_MIR(    'photosMIR.xml')
df_pascal = parse_photos_PASCAL( 'photosPASCAL.xml')

# 2) Keep the same columns in the same order
cols = [
  'photo_id','dateuploaded',
  'latitude','longitude',
  'title','description',
  'owner_username','user_id','owner_location'
]
df_clef   = df_clef[cols]
df_mir    = df_mir[cols]
df_pascal = df_pascal[cols]

# 3) Concatenate
df_all = pd.concat([df_clef, df_mir, df_pascal], ignore_index=True)

# 4) Save out for downstream steps
df_all.to_pickle('df_all.pkl')
df_all.to_csv(   'merged_photos.csv', index=False)

# 5) Sanity check
print("Merged shape:", df_all.shape)
df_all.head(10)

Merged shape: (29195, 9)

,photo_id,dateuploaded,latitude,longitude,title,description,owner_username,user_id,owner_location
0,2109698205,2007-12-14 07:44:18,37.794833,-122.401334,Launch Day donuts,"Hello, Stats! Hello, Uploadrrrrrr!",waferbaby,51035718466@N01,"San Francisco, USA"
1,2172469872,2008-01-06 17:07:08,NaN,NaN,Old and Knackered,"Don't fret about which is which, it's pretty m...",me'nthedogs,66176388@N00,"Williton, UK"
2,830593398,2007-07-16 19:04:27,NaN,NaN,Boats,None,Monster.,66201174@N00,
3,2226919732,2008-01-28 20:07:00,55.765685,37.630110,Отпевание,"Чин погребения приснопамятного <a target=""_bla...",И. Максим,16185355@N00,France
4,798067744,2007-07-13 10:22:26,NaN,NaN,Precarious,"Lake Phalen, Maplewood, MN",*clairity*,38315261@N00,
5,2162084627,2008-01-03 14:50:11,NaN,NaN,Inquietudine.,Il mio primo scatto con la nuova Nikon D40.\nN...,LunaDiRimmel,77251992@N00,
6,2516831585,2008-05-24 01:31:22,NaN,NaN,Capter,None,pichenettes,52163187@N00,"Paris, France"
7,2145166304,2007-12-28 23:38:32,NaN,NaN,last ferry of the day,None,g_cowan,32399776@N00,"ardrossan, scotland"
8,2330883810,2008-03-13 07:51:26,NaN,NaN,Line 'em up just to knock 'em down,None,unsure shot,46162062@N00,Los Angeles
9,1912488787,2007-11-08 04:52:37,NaN,NaN,Rainbow Bookcase,I aligned my books in honor of the Rainbow Sna...,Eccentric Scholar,7772579@N08,"Durham, NC, US"

In [ ]:
import pandas as pd

# 1) Load your merged data (adjust path if needed)
# df = pd.read_pickle('df_all.pkl')
df = pd.read_csv('merged_photos.csv', parse_dates=['dateuploaded'])

# 2) Drop any rows missing geo or timestamp
df = df.dropna(subset=['dateuploaded','latitude','longitude'])
print(f"Photos with geo‐tags: {len(df)} / 29195")

# 3) (Optional) Inspect a few
print(df[['user_id','dateuploaded','latitude','longitude']].head())

Photos with geo‐tags: 6479 / 29195
            user_id        dateuploaded   latitude   longitude
0   51035718466@N01 2007-12-14 07:44:18  37.794833 -122.401334
3      16185355@N00 2008-01-28 20:07:00  55.765685   37.630110
10      8227090@N04 2008-05-20 19:04:46  45.756138    4.839649
11     68268595@N00 2008-03-11 16:37:37 -32.030490  115.826346
13     12734746@N00 2008-02-29 15:02:40  25.788550  -80.189359

In [ ]:
import pandas as pd
import math
from IPython.display import display

# 1) Load & filter to only geo‑tagged photos
df = pd.read_csv('merged_photos.csv', parse_dates=['dateuploaded'])
df = df.dropna(subset=['dateuploaded','latitude','longitude'])
df = df.sort_values('dateuploaded').reset_index(drop=True)
print(f"Using {len(df)} geotagged photos (of 29195 total)")

# 2) Inline Haversine function (returns km)
def haversine_km(c1, c2):
    # c1, c2 = (lat, lon) in decimal degrees
    lat1, lon1 = math.radians(c1[0]), math.radians(c1[1])
    lat2, lon2 = math.radians(c2[0]), math.radians(c2[1])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = (math.sin(dlat/2)**2 +
         math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2)
    return 6371.0 * 2 * math.asin(math.sqrt(a))

# 3) Sliding‐window co‑occurrence counter
def count_pairs(delta_t, delta_d_km):
    pairs = {}
    start = 0
    n = len(df)
    for i in range(n):
        t_i = df.at[i, 'dateuploaded']
        # advance window start so that dateuploaded[j] ≥ t_i - delta_t
        while df.at[start, 'dateuploaded'] < t_i - delta_t:
            start += 1
        for j in range(start, i):
            if df.at[j, 'user_id'] == df.at[i, 'user_id']:
                continue
            u, v = df.at[i,'user_id'], df.at[j,'user_id']
            pair = tuple(sorted((u, v)))
            coord_i = (df.at[i,'latitude'], df.at[i,'longitude'])
            coord_j = (df.at[j,'latitude'], df.at[j,'longitude'])
            if haversine_km(coord_i, coord_j) <= delta_d_km:
                pairs[pair] = pairs.get(pair, 0) + 1
    return pairs

# 4) Debug counts at different distance thresholds
delta_t = pd.Timedelta(hours=1)
print("\nTesting co‑occurrences at various distance thresholds:")
for d in [0.1, 0.5, 1.0]:  # 100 m, 500 m, 1 km
    p = count_pairs(delta_t, d)
    print(f"  Δd = {d} km → {len(p)} user‑pairs")

# 5) Pick the threshold that yields >0 (e.g., 0.5 km) and save results
chosen_d = 100
pairs = count_pairs(delta_t, chosen_d)

coocc_df = pd.DataFrame([
    {'user_u': u, 'user_v': v, 'cooccurrence_count': cnt}
    for (u, v), cnt in pairs.items()
])

# Save to CSV
coocc_df.to_csv('user_cooccurrences.csv', index=False)

# Make sure pandas will show all rows
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Display every co‑occurring pair
print(f"Found {len(coocc_df)} co‑occurring pairs at Δd={chosen_d} km, Δt=1 h:")
display(coocc_df)

Using 6479 geotagged photos (of 29195 total)

Testing co‑occurrences at various distance thresholds:
  Δd = 0.1 km → 0 user‑pairs
  Δd = 0.5 km → 0 user‑pairs
  Δd = 1.0 km → 0 user‑pairs
Found 21 co‑occurring pairs at Δd=100 km, Δt=1 h:

             user_u           user_v  cooccurrence_count
0      79148947@N00     84253456@N00                   1
1      25362125@N00     63726798@N00                   1
2      23069082@N00     88111659@N00                   1
3       7371031@N08     89086130@N00                   1
4      26887305@N00  41894166582@N01                   2
5      19762676@N00     29312235@N00                   1
6      55064893@N00     57552634@N00                   1
7      10177557@N08      7970047@N08                   1
8      72429059@N00     92566565@N00                   1
9      28885794@N00     54459164@N00                   1
10     10588069@N00     90569898@N00                   1
11     19311544@N00     93593197@N00                   1
12  37718677955@N01     95797890@N00                   2
13     18215054@N06     83479321@N00                   3
14     11946969@N00     75363214@N00                   1
15     15703741@N04      7582162@N08                   2
16     17676866@N00     41942132@N00                   4
17  32373682187@N01     33473816@N00                   4
18      8088927@N06     82547163@N00                   4
19     23965202@N06     98347787@N00                   2
20     10278395@N08     15462727@N07                   1

In [ ]:
!pip install haversine

Collecting haversine
  Downloading haversine-2.9.0-py2.py3-none-any.whl.metadata (5.8 kB)
Downloading haversine-2.9.0-py2.py3-none-any.whl (7.7 kB)
Installing collected packages: haversine
Successfully installed haversine-2.9.0

In [ ]:
!pwd
!ls -R .

/content
.:
df_all.pkl	 merged_photos.csv  photosMIR.xml     sample_data
flickrEdges.txt  photosCLEF.xml     photosPASCAL.xml  user_cooccurrences.csv

./sample_data:
anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md

In [ ]:
df = df.dropna(subset=['dateuploaded','latitude','longitude'])
print("Clean records:", len(df))

Clean records: 6479

In [ ]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
import pandas as pd
import math
import networkx as nx
import numpy as np
import random
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, f1_score, classification_report
from IPython.display import display

# 1) Load & filter your merged photo DataFrame
df = pd.read_pickle('df_all.pkl')  # or use CSV: pd.read_csv('merged_photos.csv', parse_dates=['dateuploaded'])
df = df.dropna(subset=['dateuploaded', 'latitude', 'longitude'])
df['user_id'] = df['user_id'].astype(str)
df = df.sort_values('dateuploaded').reset_index(drop=True)
print(f"Using {len(df)} geotagged photos")

# 2) Inline Haversine function (km)
def haversine_km(c1, c2):
    lat1, lon1 = math.radians(c1[0]), math.radians(c1[1])
    lat2, lon2 = math.radians(c2[0]), math.radians(c2[1])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 6371.0 * 2 * math.asin(math.sqrt(a))

# 3) Count spatio‑temporal co‑occurrences
def count_pairs(delta_t, delta_d_km):
    pairs = {}
    start = 0
    n = len(df)
    for i in range(n):
        t_i = df.at[i, 'dateuploaded']
        while df.at[start, 'dateuploaded'] < t_i - delta_t:
            start += 1
        for j in range(start, i):
            u = str(df.at[i, 'user_id'])
            v = str(df.at[j, 'user_id'])
            if u == v:
                continue
            pair = tuple(sorted((u, v)))
            coord_i = (df.at[i, 'latitude'], df.at[i, 'longitude'])
            coord_j = (df.at[j, 'latitude'], df.at[j, 'longitude'])
            if haversine_km(coord_i, coord_j) <= delta_d_km:
                pairs[pair] = pairs.get(pair, 0) + 1
    return pairs

delta_t = pd.Timedelta(hours=1)
chosen_d = 100  # km threshold
pairs = count_pairs(delta_t, chosen_d)

coocc_df = pd.DataFrame([
    {'user_u': u, 'user_v': v, 'cooccurrence_count': cnt}
    for (u, v), cnt in pairs.items()
])
coocc_df.to_csv('user_cooccurrences.csv', index=False)
print(f"Saved {len(coocc_df)} co‑occurring pairs (Δd={chosen_d} km, Δt=1h)")
display(coocc_df)

# 4) Load Flickr friendship edges and cast to string
edges_df = pd.read_csv('flickrEdges.txt', sep='\t', header=None, names=['u', 'v'])
edges_df['u'] = edges_df['u'].astype(str)
edges_df['v'] = edges_df['v'].astype(str)
G = nx.Graph()
G.add_edges_from(edges_df.values)
print(f"\nFriendship graph: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")

# 5) Prepare examples for link prediction
pos = list(G.edges())
nodes = list(G.nodes())
neg = []
while len(neg) < len(pos):
    u, v = random.sample(nodes, 2)
    if not G.has_edge(u, v):
        neg.append((u, v))
pairs_all = pos + neg
labels = [1] * len(pos) + [0] * len(neg)

# 6) Build feature matrix (CN, Jaccard, AA, PA, cooccurrence)
coocc_dict = {
    tuple(sorted((str(r.user_u), str(r.user_v)))): r.cooccurrence_count
    for r in coocc_df.itertuples()
}

# Convert pairs to str and prepare labels
pairs_all = [(str(u), str(v)) for u, v in pos + neg]
labels = [1]*len(pos) + [0]*len(neg)

# Precompute features
cn_dict = {pair: len(list(nx.common_neighbors(G, *pair))) for pair in pairs_all}
aa_scores = {(u, v): p for u, v, p in nx.adamic_adar_index(G, pairs_all)}
pa_scores = {(u, v): p for u, v, p in nx.preferential_attachment(G, pairs_all)}
co_scores = {tuple(sorted((u, v))): coocc_dict.get(tuple(sorted((u, v))), 0)
             for u, v in pairs_all}

# Build final feature matrix
X = np.array([
    [cn_dict.get((u, v), 0),
     aa_scores.get((u, v), 0),
     pa_scores.get((u, v), 0),
     co_scores.get((u, v), 0)]
    for u, v in pairs_all
])
y = np.array(labels)

# 7) Train/test split & classifier
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)
clf = LogisticRegression(max_iter=1000).fit(X_train, y_train)

# 8) Evaluate
y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:, 1]
print("\n--- Evaluation Metrics ---")
print("ROC‑AUC:", roc_auc_score(y_test, y_prob))
print("F1 Score:", f1_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Using 6479 geotagged photos
Saved 21 co‑occurring pairs (Δd=100 km, Δt=1h)

             user_u           user_v  cooccurrence_count
0      79148947@N00     84253456@N00                   1
1      25362125@N00     63726798@N00                   1
2      23069082@N00     88111659@N00                   1
3       7371031@N08     89086130@N00                   1
4      26887305@N00  41894166582@N01                   2
5      19762676@N00     29312235@N00                   1
6      55064893@N00     57552634@N00                   1
7      10177557@N08      7970047@N08                   1
8      72429059@N00     92566565@N00                   1
9      28885794@N00     54459164@N00                   1
10     10588069@N00     90569898@N00                   1
11     19311544@N00     93593197@N00                   1
12  37718677955@N01     95797890@N00                   2
13     18215054@N06     83479321@N00                   3
14     11946969@N00     75363214@N00                   1
15     15703741@N04      7582162@N08                   2
16     17676866@N00     41942132@N00                   4
17  32373682187@N01     33473816@N00                   4
18      8088927@N06     82547163@N00                   4
19     23965202@N06     98347787@N00                   2
20     10278395@N08     15462727@N07                   1

Friendship graph: 2316953 nodes, 2316952 edges

--- Evaluation Metrics ---
ROC‑AUC: 1.0
F1 Score: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    695086
           1       1.00      1.00      1.00    695086

    accuracy                           1.00   1390172
   macro avg       1.00      1.00      1.00   1390172
weighted avg       1.00      1.00      1.00   1390172

In [ ]:
# 8) Evaluate
y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:, 1]
print("\n--- Evaluation Metrics ---")
print("ROC‑AUC:", roc_auc_score(y_test, y_prob))
print("F1 Score:", f1_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

--- Evaluation Metrics ---
ROC‑AUC: 1.0
F1 Score: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    695086
           1       1.00      1.00      1.00    695086

    accuracy                           1.00   1390172
   macro avg       1.00      1.00      1.00   1390172
weighted avg       1.00      1.00      1.00   1390172

In [ ]:
print("Duplicates between pos and neg:", len(set(pos) & set(neg)))

Duplicates between pos and neg: 0

In [ ]:
import pandas as pd

# Load photo metadata with user ID and GPS
df = pd.read_csv("merged_photos.csv", parse_dates=["dateuploaded"])
df = df.dropna(subset=['latitude', 'longitude', 'user_id'])
df['user_id'] = df['user_id'].astype(str)

# Create mapping: user_id → list of (lat, lon) tuples
user_locations = df.groupby('user_id')[['latitude', 'longitude']].apply(
    lambda x: list(x.itertuples(index=False))
).to_dict()

In [ ]:
import pandas as pd
import networkx as nx

# Load co-occurrence data (from cooccurrence_counts.csv or user_cooccurrences.csv)
coocc_df = pd.read_csv("user_cooccurrences.csv")  # or "user_cooccurrences.csv"
if 'user_u' in coocc_df.columns:
    coocc_dict = {
        tuple(sorted((str(row.user_u), str(row.user_v)))): row.cooccurrence_count
        for row in coocc_df.itertuples()
    }
else:
    coocc_dict = {
        tuple(sorted((str(row.userA), str(row.userB)))): row.k
        for row in coocc_df.itertuples()
    }

G_co = nx.Graph()
for (u, v), count in coocc_dict.items():
    G_co.add_edge(u, v, weight=count)

# Get top 100 edges by weight
top_edges = sorted(G_co.edges(data=True), key=lambda x: -x[2]['weight'])[:100]

# Convert to DataFrame
top_100_df = pd.DataFrame([
    {'User A': u, 'User B': v, 'Co-occurrence Count': d['weight']}
    for u, v, d in top_edges
]).sort_values(by='Co-occurrence Count', ascending=False).reset_index(drop=True)

# Display or save
print(top_100_df.head(10))  # or use display(top__df) in notebooks
top_100_df.to_csv("top_cooccurrences.csv", index=False)

            User A           User B  Co-occurrence Count
0     17676866@N00     41942132@N00                    4
1  32373682187@N01     33473816@N00                    4
2      8088927@N06     82547163@N00                    4
3     18215054@N06     83479321@N00                    3
4     26887305@N00  41894166582@N01                    2
5  37718677955@N01     95797890@N00                    2
6     15703741@N04      7582162@N08                    2
7     23965202@N06     98347787@N00                    2
8     79148947@N00     84253456@N00                    1
9     25362125@N00     63726798@N00                    1

In [ ]:
import pandas as pd
import math

# Load photo metadata
df = pd.read_csv("merged_photos.csv", parse_dates=["dateuploaded"])
df = df.dropna(subset=['latitude', 'longitude', 'user_id'])
df['user_id'] = df['user_id'].astype(str)

# Create user_id → [(lat, lon), ...] mapping
user_locations = df.groupby('user_id')[['latitude', 'longitude']].apply(
    lambda x: list(x.itertuples(index=False))
).to_dict()

# Load co-occurrence data
coocc_df = pd.read_csv("user_cooccurrences.csv")
coocc_dict = {
    tuple(sorted((str(row.user_u), str(row.user_v)))): row.cooccurrence_count
    for row in coocc_df.itertuples()
}

# Haversine distance (km)
def haversine_km(c1, c2):
    lat1, lon1 = math.radians(c1[0]), math.radians(c1[1])
    lat2, lon2 = math.radians(c2[0]), math.radians(c2[1])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1)*math.cos(lat2)*math.sin(dlon/2)**2
    return 6371.0 * 2 * math.asin(math.sqrt(a))

# Suggest co-occurring users (with or without existing connections)
def suggest_friends_include_all(user_id, coocc_dict, user_locations, top_n=5):
    user_id = str(user_id)
    suggestions = []

    for (u, v), count in coocc_dict.items():
        if user_id not in (u, v):
            continue
        other = v if u == user_id else u

        coords_u = user_locations.get(user_id, [])
        coords_v = user_locations.get(other, [])
        if not coords_u or not coords_v:
            continue

        total_dist = 0
        num = 0
        for c1 in coords_u:
            for c2 in coords_v:
                total_dist += haversine_km(c1, c2)
                num += 1
        avg_dist = total_dist / num if num > 0 else float('inf')
        suggestions.append((other, count, avg_dist))

    ranked = sorted(suggestions, key=lambda x: (-x[1], x[2]))[:top_n]
    return pd.DataFrame(ranked, columns=["Suggested User", "Co-occurrence Count", "Avg Distance (km)"])

# ▶️ Try it with a sample user from your data
sample_user = "8088927@N06"  # Replace with any real user_id from your dataset

suggested_df = suggest_friends_include_all(sample_user, coocc_dict, user_locations, top_n=5)
print(f"\n Top Friend Suggestions for {sample_user}")
print(suggested_df)

 Top Friend Suggestions for 8088927@N06
  Suggested User  Co-occurrence Count  Avg Distance (km)
0   82547163@N00                    4         690.493024